<?php

namespace OC\GameCriticBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get latest games
     * 
     * @param int $start
     * @param int $limit
     * @return array
     */
    public function getLatestGames($start, $limit)
    {
        if (!is_int($start) || $start < 0) {
            throw new \Exception('Invalid start parameter');
        } elseif (!is_int($limit) || $limit < 1) {
            throw new \Exception('Invalid limit parameter');
        }
        
        $query = $this->_em->createQuery('
SELECT g 
FROM OCGameCriticBundle:Game g 
ORDER BY g.releaseDate DESC
');
        $query->setFirstResult($start);
        $query->setMaxResults($limit);

        return $query->getResult();
    }
}
