<?php

namespace OC\GameCriticBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get latest games
     * 
     * @param int $page
     * @param int $limit
     * @return Paginator
     */
    public function getLatestGames($page, $nbPerPage)
    {
        if ($page < 1) {
            throw new \Exception('Invalid page parameter');
        } elseif ($nbPerPage < 1) {
            throw new \Exception('Invalid nbPerPage parameter');
        }
        
        $query = $this->_em->createQuery('
SELECT g 
FROM OCGameCriticBundle:Game g 
ORDER BY g.releaseDate DESC
');
        $query->setFirstResult(($page - 1) * $nbPerPage);
        $query->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

    /**
     * Get total games
     *
     * @return int
     */
    public function getTotalGames()
    {
        $query = $this->_em->createQuery('
SELECT COUNT(g) 
FROM OCGameCriticBundle:Game g 
');

        return (int) $query->getSingleScalarResult();
    }
}
