oc_game_critic_game:
    resource: "@OCGameCriticBundle/Resources/config/routing/game.yml"
    prefix:   /game

oc_game_critic_homepage:
    path:     /
    defaults: { _controller: OCGameCriticBundle:Game:index }
